services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:123@db:5432/expenses
    ports:
      - "3000:3000"
    volumes:
      - ./db/db.csv:/app/db/db.csv
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
